### PR TITLE
Pull Request for Newsweek Bootstrap Clone Review

### PR DESCRIPTION
**Pull request by Calvinoea**
Hello. I am making a pull request for a code review for the Newsweek Bootstrap clone project, a responsive clone of [Newsweek](https://newsweek.com/) . The page has been made using Bootstrap 4, Font Awesome,HTML, CSS and  guidelines provided. 

Because of the responsive nature of websites made using Bootstrap 4 framework, users are able to look at the site on different sized screens and browsers, including mobile and desktop applications.

[W3](https://validator.w3.org/) was used to carry out HTML validation and Stickler was used for highlighting issues with styling

Thank you to the engineers who carried out the review of the project, Luis Preza and Suman Shrestha. 

Changes made following TSE review include:

- Reduction of whitespace in the top section
- Image alignment in the subscription section
- Removal of unwanted headings
- Changing of background colour
- Improvement of responsiveness in the magazine section
- Addition of different images and headings

Please find below a link to the live project:

[Newsweek Clone](https://amazing-colden-99bae9.netlify.com/)

### CODE REVIEW

**Review by men32z — CHANGES_REQUESTED** [review]
Hey @Calvinoea !
## Awesome job on this project! 👍
you really did a great job here, that's why I'm going to be strict with you.

There are some changes 👇 you need to implement to approve this request 🔍

#### Required changes
Remember that this project is a clone page, and should be as closest as possible to the original one. 

- [ ] change the description of your PR, remember that should be something descriptive, you can add the features of the project, such as responsiveness, number of sections, and maybe the description of the nice implementation of the search bar effect you did.

- [ ] In wide versions, the background of the page should be visible with another kind of gray color. check this screenshot.
asdfasdf

- [ ] there is a problem that is causing a big white space in Firefox, although is not a problem in chrome it is a good practice be aware that actually works in all browsers.
kindly fix it.
bbbbb

- [ ] at some point between the middle and mobile versions, the image in this section before footer disappears. kindly fix this issue.

Screenshot_2020-04-03 Newsweek- News, Analysis, Politics, Business, Technology

- [ ] titles in Featured Stories should be bold.

- [ ] add different titles and images to all sections so it would less like a template. 

- [ ] try to fix the spaces between the sections, in the original page this was made with JS but you could make a trick with an overflow scroll hidden property to make it look similar.

Screenshot_2020-04-03 Newsweek

#### for the next project
- [ ] add descriptive commits ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) remember if you dont do it this could be a reason for project rejection.

- [ ] use stickler or ask microverse for let you use your own style validator and add that in the PR.

## Please, make all REQUIRED changes and submit your request again! 😀
like I said you did a great project, keep working hard :muscle:

If you have any questions, feel free to send me a message through Slack (@men32z)
I would be happy to help! 👩‍💻

Happy coding 🤓

--Luis Preza

**Comment by Calvinoea** [comment]
> Hey @Calvinoea !
> 
> ## Awesome job on this project! 👍
> you really did a great job here, that's why I'm going to be strict with you.
> 
> There are some changes 👇 you need to implement to approve this request 🔍
> 
> #### Required changes
> Remember that this project is a clone page, and should be as closest as possible to the original one.
> 
> * [ ]  change the description of your PR, remember that should be something descriptive, you can add the features of the project, such as responsiveness, number of sections, and maybe the description of the nice implementation of the search bar effect you did.
> * [ ]  In wide versions, the background of the page should be visible with another kind of gray color. check this screenshot.
>   asdfasdf
> * [ ]  there is a problem that is causing a big white space in Firefox, although is not a problem in chrome it is a good practice be aware that actually works in all browsers.
>   kindly fix it.
>   bbbbb
> * [ ]  at some point between the middle and mobile versions, the image in this section before footer disappears. kindly fix this issue.
> 
> Screenshot_2020-04-03 Newsweek- News, Analysis, Politics, Business, Technology
> 
> * [ ]  titles in Featured Stories should be bold.
> * [ ]  add different titles and images to all sections so it would less like a template.
> * [ ]  try to fix the spaces between the sections, in the original page this was made with JS but you could make a trick with an overflow scroll hidden property to make it look similar.
> 
> Screenshot_2020-04-03 Newsweek
> 
> #### for the next project
> * [ ]  add descriptive commits ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) remember if you dont do it this could be a reason for project rejection.
> * [ ]  use stickler or ask microverse for let you use your own style validator and add that in the PR.
> 
> ## Please, make all REQUIRED changes and submit your request again! 😀
> like I said you did a great project, keep working hard 💪
> 
> If you have any questions, feel free to send me a message through Slack (@men32z)
> I would be happy to help! 👩‍💻
> 
> Happy coding 🤓
> 
> --Luis Preza

Hello Luis. Thank you for your review. I am working on the changes.

**Comment by sumancrest0001** [comment]
**STATUS: CHANGES REQUIRED**

**You have done a great job to fix issues addressed by previous TSEs :+1: :+1:** 

But still, We have to fix a couple of minor issues to make it a perfect clone of the original site.
Kindly make the following changes and submit for another review :point_down:  :point_down:
 
[REQUIRED] There is an empty space on the large screen. Please fix this issue. :point_down: 
Screenshot from 2020-04-05 20-30-41

**Comment by sumancrest0001** [comment]
[REQUIRED] Please remove the title (lorem) from the magazine, U.S other similar sections. Have a look.
in your project :point_down:  :point_down: 
Screenshot from 2020-04-05 20-31-27

It should be :point_down: 
Screenshot from 2020-04-05 20-31-46

**Comment by sumancrest0001** [comment]
[REQUIRED] Align both images like
 that of the orignal page.

in your project :point_down:  :point_down: 
Screenshot from 2020-04-05 20-32-37

in the original project :point_down:  :point_down: 
Screenshot from 2020-04-05 20-32-54

**Comment by sumancrest0001** [comment]
[REQUIRED] on the small screen, the magazine section is not responsive.

in your project :point_down: 
Screenshot from 2020-04-05 20-41-12

It should be like this :point_down: :point_down: 
Screenshot from 2020-04-05 20-41-38

**Comment by sumancrest0001** [comment]
**[Optional changes] These changes are not compulsory but nice to have**

-Use more bootstrap classes for stylings instead of custom CSS.
-Add sticky navbar for all screen sizes to make it similar to the original one.
-Add a little bit of description while creating a PR. It could be features you added or changes you made.

**Comment by sumancrest0001** [comment]
**All the best for another review.**:+1:
Need help? feel free to message me on slack. **suman shrestha**

**Comment by Calvinoea** [comment]
> **All the best for another review.**👍
> Need help? feel free to message me on slack. **suman shrestha**

Hello @sumancrest0001  .Thank you for your review. The changes are being made.

**Comment by uryelah** [comment]
Hello **Calvin Ebun-Amu**, I'm Sarah, your last reviewer for this PR 👩‍🚀  

You did a great job with this project, it's fully responsive and it's using bootstrap nicely.

------
## Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

----

**Keep being an awesome dev and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by Calvinoea** [comment]
> Hello **Calvin Ebun-Amu**, I'm Sarah, your last reviewer for this PR 👩‍🚀
> 
> You did a great job with this project, it's fully responsive and it's using bootstrap nicely.
> 
> ## Your project is approved! 🎊 🥅 💛
> **You may close this Pull Request and merge the changes**
> 
> **Keep being an awesome dev and good luck with your next project!**
> 
> Cheers and Happy coding!👏👏👏
> 
> Code review by **Sarah Uryelah Silva Chamorro**
> 
> (Feel free to contact me on slack by the handle of **sarah** if you have any additional question)

Hey Sarah, thank you 

> Hello **Calvin Ebun-Amu**, I'm Sarah, your last reviewer for this PR 👩‍🚀
> 
> You did a great job with this project, it's fully responsive and it's using bootstrap nicely.
> 
> ## Your project is approved! 🎊 🥅 💛
> **You may close this Pull Request and merge the changes**
> 
> **Keep being an awesome dev and good luck with your next project!**
> 
> Cheers and Happy coding!👏👏👏
> 
> Code review by **Sarah Uryelah Silva Chamorro**
> 
> (Feel free to contact me on slack by the handle of **sarah** if you have any additional question)

Hello Sarah. Thank you for your review 🙏 🙏 🙏 💛

> Hello **Calvin Ebun-Amu**, I'm Sarah, your last reviewer for this PR 👩‍🚀
> 
> You did a great job with this project, it's fully responsive and it's using bootstrap nicely.
> 
> ## Your project is approved! 🎊 🥅 💛
> **You may close this Pull Request and merge the changes**
> 
> **Keep being an awesome dev and good luck with your next project!**
> 
> Cheers and Happy coding!👏👏👏
> 
> Code review by **Sarah Uryelah Silva Chamorro**
> 
> (Feel free to contact me on slack by the handle of **sarah** if you have any additional question)

Hello, Sarah. Thank you for your review and approval. 🙏 🙏 💛💛

**Pull request merged**
